// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.address_type_enum */
enum AddressTypeEnum {
  shipping = 'shipping',
  billing = 'billing',
};

export default AddressTypeEnum;
