// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.categories */
export type CategoriesId = string & { __brand: 'public.categories' };

/** Represents the table public.categories */
export default interface Categories {
  id: CategoriesId;

  name: string;

  description: string | null;

  parent_category_id: CategoriesId | null;

  image_url: string | null;

  is_active: boolean | null;

  created_at: Date;
}

/** Represents the initializer for the table public.categories */
export interface CategoriesInitializer {
  id: CategoriesId;

  name: string;

  description?: string | null;

  parent_category_id?: CategoriesId | null;

  image_url?: string | null;

  /** Default value: true */
  is_active?: boolean | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.categories */
export interface CategoriesMutator {
  id?: CategoriesId;

  name?: string;

  description?: string | null;

  parent_category_id?: CategoriesId | null;

  image_url?: string | null;

  is_active?: boolean | null;

  created_at?: Date;
}
