// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.currencies */
export type CurrenciesId = string & { __brand: 'public.currencies' };

/** Represents the table public.currencies */
export default interface Currencies {
  id: CurrenciesId;

  code: string;

  name: string;

  symbol: string;

  decimal_places: number;

  is_active: boolean;

  created_at: Date;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.currencies */
export interface CurrenciesInitializer {
  /** Default value: nextval('currencies_id_seq'::regclass) */
  id?: CurrenciesId;

  code: string;

  name: string;

  symbol: string;

  /** Default value: 2 */
  decimal_places?: number;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  updated_at?: Date | null;
}

/** Represents the mutator for the table public.currencies */
export interface CurrenciesMutator {
  id?: CurrenciesId;

  code?: string;

  name?: string;

  symbol?: string;

  decimal_places?: number;

  is_active?: boolean;

  created_at?: Date;

  updated_at?: Date | null;
}
