// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CurrenciesId } from './Currencies';

/** Identifier type for public.exchange_rates */
export type ExchangeRatesId = string & { __brand: 'public.exchange_rates' };

/** Represents the table public.exchange_rates */
export default interface ExchangeRates {
  id: ExchangeRatesId;

  from_currency_id: CurrenciesId;

  to_currency_id: CurrenciesId;

  rate: string;

  effective_date: Date;

  created_at: Date;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.exchange_rates */
export interface ExchangeRatesInitializer {
  /** Default value: nextval('exchange_rates_id_seq'::regclass) */
  id?: ExchangeRatesId;

  from_currency_id: CurrenciesId;

  to_currency_id: CurrenciesId;

  rate: string;

  /** Default value: CURRENT_TIMESTAMP */
  effective_date?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  updated_at?: Date | null;
}

/** Represents the mutator for the table public.exchange_rates */
export interface ExchangeRatesMutator {
  id?: ExchangeRatesId;

  from_currency_id?: CurrenciesId;

  to_currency_id?: CurrenciesId;

  rate?: string;

  effective_date?: Date;

  created_at?: Date;

  updated_at?: Date | null;
}
