// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProductVariantsId } from './ProductVariants';

/** Identifier type for public.inventory */
export type InventoryId = string & { __brand: 'public.inventory' };

/** Represents the table public.inventory */
export default interface Inventory {
  id: InventoryId;

  product_variant_id: ProductVariantsId;

  quantity_available: number;

  quantity_reserved: number;

  reorder_level: number;

  last_updated: Date;
}

/** Represents the initializer for the table public.inventory */
export interface InventoryInitializer {
  id: InventoryId;

  product_variant_id: ProductVariantsId;

  quantity_available: number;

  quantity_reserved: number;

  reorder_level: number;

  /** Default value: CURRENT_TIMESTAMP */
  last_updated?: Date;
}

/** Represents the mutator for the table public.inventory */
export interface InventoryMutator {
  id?: InventoryId;

  product_variant_id?: ProductVariantsId;

  quantity_available?: number;

  quantity_reserved?: number;

  reorder_level?: number;

  last_updated?: Date;
}
