// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { OrdersId } from "./Orders";
import type { ProductVariantsId } from "./ProductVariants";
import type { SellersId } from "./Sellers";
import type { default as OrderStatusEnum } from "./OrderStatusEnum";

/** Identifier type for public.order_items */
export type OrderItemsId = string & { __brand: "public.order_items" };

/** Represents the table public.order_items */
export default interface OrderItems {
  id: OrderItemsId;

  order_id: OrdersId;

  product_variant_id: ProductVariantsId;

  seller_id: SellersId;

  quantity: number;

  unit_price: string;

  total_price: string;

  item_status: OrderStatusEnum;
}

/** Represents the initializer for the table public.order_items */
export interface OrderItemsInitializer {
  /** Default value: nextval('order_items_id_seq'::regclass) */
  id: OrderItemsId;

  order_id: OrdersId;

  product_variant_id: ProductVariantsId;

  seller_id: SellersId;

  quantity: number;

  unit_price: string;

  total_price: string;

  item_status: OrderStatusEnum;
}

/** Represents the mutator for the table public.order_items */
export interface OrderItemsMutator {
  id?: OrderItemsId;

  order_id?: OrdersId;

  product_variant_id?: ProductVariantsId;

  seller_id?: SellersId;

  quantity?: number;

  unit_price?: string;

  total_price?: string;

  item_status?: OrderStatusEnum;
}
