// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.order_status_enum */
enum OrderStatusEnum {
  pending = 'pending',
  confirmed = 'confirmed',
  processing = 'processing',
  shipped = 'shipped',
  delivered = 'delivered',
  cancelled = 'cancelled',
  refunded = 'refunded',
};

export default OrderStatusEnum;
