// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';
import type { default as OrderStatusEnum } from './OrderStatusEnum';

/** Identifier type for public.orders */
export type OrdersId = string & { __brand: 'public.orders' };

/** Represents the table public.orders */
export default interface Orders {
  id: OrdersId;

  user_id: UsersId;

  order_number: string;

  subtotal: string;

  tax_amount: string;

  shipping_amount: string;

  discount_amount: string;

  total_amount: string;

  order_status: OrderStatusEnum;

  order_date: Date;

  status: string;

  estimated_delivery: Date | null;

  shipping_address: unknown;

  billing_address: unknown;

  created_at: Date;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.orders */
export interface OrdersInitializer {
  id: OrdersId;

  user_id: UsersId;

  order_number: string;

  subtotal: string;

  tax_amount: string;

  shipping_amount: string;

  discount_amount: string;

  total_amount: string;

  order_status: OrderStatusEnum;

  /** Default value: CURRENT_TIMESTAMP */
  order_date?: Date;

  status: string;

  /** Default value: CURRENT_TIMESTAMP */
  estimated_delivery?: Date | null;

  shipping_address: unknown;

  billing_address: unknown;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  updated_at?: Date | null;
}

/** Represents the mutator for the table public.orders */
export interface OrdersMutator {
  id?: OrdersId;

  user_id?: UsersId;

  order_number?: string;

  subtotal?: string;

  tax_amount?: string;

  shipping_amount?: string;

  discount_amount?: string;

  total_amount?: string;

  order_status?: OrderStatusEnum;

  order_date?: Date;

  status?: string;

  estimated_delivery?: Date | null;

  shipping_address?: unknown;

  billing_address?: unknown;

  created_at?: Date;

  updated_at?: Date | null;
}
