// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.payment_status_enum */
enum PaymentStatusEnum {
  pending = 'pending',
  completed = 'completed',
  failed = 'failed',
  refunded = 'refunded',
};

export default PaymentStatusEnum;
