// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { OrdersId } from './Orders';
import type { UsersId } from './Users';
import type { default as PaymentStatusEnum } from './PaymentStatusEnum';

/** Identifier type for public.payments */
export type PaymentsId = string & { __brand: 'public.payments' };

/** Represents the table public.payments */
export default interface Payments {
  id: PaymentsId;

  order_id: OrdersId;

  user_id: UsersId;

  amount: string;

  payment_method: string;

  payment_provider: string;

  transaction_id: string;

  payment_status: PaymentStatusEnum;

  payment_date: Date;
}

/** Represents the initializer for the table public.payments */
export interface PaymentsInitializer {
  id: PaymentsId;

  order_id: OrdersId;

  user_id: UsersId;

  amount: string;

  payment_method: string;

  payment_provider: string;

  transaction_id: string;

  payment_status: PaymentStatusEnum;

  /** Default value: CURRENT_TIMESTAMP */
  payment_date?: Date;
}

/** Represents the mutator for the table public.payments */
export interface PaymentsMutator {
  id?: PaymentsId;

  order_id?: OrdersId;

  user_id?: UsersId;

  amount?: string;

  payment_method?: string;

  payment_provider?: string;

  transaction_id?: string;

  payment_status?: PaymentStatusEnum;

  payment_date?: Date;
}
