// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProductsId } from './Products';

/** Identifier type for public.product_variants */
export type ProductVariantsId = string & { __brand: 'public.product_variants' };

/** Represents the table public.product_variants */
export default interface ProductVariants {
  id: ProductVariantsId;

  product_id: ProductsId;

  variant_name: string;

  price: string;

  sku: string;

  stock_quantity: number;

  variant_attributes: unknown;

  is_active: boolean | null;
}

/** Represents the initializer for the table public.product_variants */
export interface ProductVariantsInitializer {
  id: ProductVariantsId;

  product_id: ProductsId;

  variant_name: string;

  price: string;

  sku: string;

  /** Default value: 0 */
  stock_quantity?: number;

  variant_attributes: unknown;

  /** Default value: true */
  is_active?: boolean | null;
}

/** Represents the mutator for the table public.product_variants */
export interface ProductVariantsMutator {
  id?: ProductVariantsId;

  product_id?: ProductsId;

  variant_name?: string;

  price?: string;

  sku?: string;

  stock_quantity?: number;

  variant_attributes?: unknown;

  is_active?: boolean | null;
}
