// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { SellersId } from "./Sellers";
import type { CategoriesId } from "./Categories";

/** Identifier type for public.products */
export type ProductsId = string & { __brand: "public.products" };

/** Represents the table public.products */
export default interface Products {
  id: ProductsId;

  seller_id: SellersId;

  category_id: CategoriesId;

  name: string;

  description: string;

  base_price: string;

  sku: string;

  brand: string | null;

  weight: string | null;

  dimensions: string | null;

  is_active: boolean | null;
  slug: string;

  created_at: Date;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.products */
export interface ProductsInitializer {
  id: ProductsId;

  seller_id: SellersId;

  category_id: CategoriesId;

  name: string;

  description: string;

  base_price: string;

  sku: string;

  brand?: string | null;

  weight?: string | null;

  dimensions?: string | null;

  /** Default value: true */
  is_active?: boolean | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  updated_at?: Date | null;
}

/** Represents the mutator for the table public.products */
export interface ProductsMutator {
  id?: ProductsId;

  seller_id?: SellersId;

  category_id?: CategoriesId;

  name?: string;

  description?: string;

  base_price?: string;

  sku?: string;

  brand?: string | null;

  weight?: string | null;

  dimensions?: string | null;

  is_active?: boolean | null;

  created_at?: Date;

  updated_at?: Date | null;
}
