// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProductsId } from './Products';

/** Identifier type for public.product_attributes */
export type ProductAttributesId = string & { __brand: 'public.product_attributes' };

/** Represents the table public.product_attributes */
export default interface ProductAttributes {
  id: ProductAttributesId;

  product_id: ProductsId;

  attribute_name: string;

  attribute_value: string;

  attribute_type: string;
}

/** Represents the initializer for the table public.product_attributes */
export interface ProductAttributesInitializer {
  id: ProductAttributesId;

  product_id: ProductsId;

  attribute_name: string;

  attribute_value: string;

  attribute_type: string;
}

/** Represents the mutator for the table public.product_attributes */
export interface ProductAttributesMutator {
  id?: ProductAttributesId;

  product_id?: ProductsId;

  attribute_name?: string;

  attribute_value?: string;

  attribute_type?: string;
}
