// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProductsId } from './Products';

/** Identifier type for public.product_images */
export type ProductImagesId = string & { __brand: 'public.product_images' };

/** Represents the table public.product_images */
export default interface ProductImages {
  id: ProductImagesId;

  product_id: ProductsId;

  image_url: string;

  alt_text: string | null;

  is_primary: boolean | null;

  sort_order: number | null;

  created_at: Date;
}

/** Represents the initializer for the table public.product_images */
export interface ProductImagesInitializer {
  id: ProductImagesId;

  product_id: ProductsId;

  image_url: string;

  alt_text?: string | null;

  /** Default value: false */
  is_primary?: boolean | null;

  /** Default value: 0 */
  sort_order?: number | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.product_images */
export interface ProductImagesMutator {
  id?: ProductImagesId;

  product_id?: ProductsId;

  image_url?: string;

  alt_text?: string | null;

  is_primary?: boolean | null;

  sort_order?: number | null;

  created_at?: Date;
}
