// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProductsId } from "./Products";
import type { UsersId } from "./Users";
import type { OrderItemsId } from "./OrderItems";

/** Identifier type for public.reviews */
export type ReviewsId = string & { __brand: "public.reviews" };

/** Represents the table public.reviews */
export default interface Reviews {
  id: ReviewsId;

  product_id: ProductsId;

  user_id: UsersId;

  order_item_id: OrderItemsId;

  rating: number;

  review_text: string;

  is_verified_purchase: boolean;

  created_at: Date;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.reviews */
export interface ReviewsInitializer {
  id: ReviewsId;

  product_id: ProductsId;

  user_id: UsersId;

  order_item_id: OrderItemsId;

  rating: number;

  review_text: string;

  is_verified_purchase: boolean;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  updated_at?: Date | null;
}

/** Represents the mutator for the table public.reviews */
export interface ReviewsMutator {
  id?: ReviewsId;

  product_id?: ProductsId;

  user_id?: UsersId;

  order_item_id?: OrderItemsId;

  rating?: number;

  review_text?: string;

  is_verified_purchase?: boolean;

  created_at?: Date;

  updated_at?: Date | null;
}
