// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { SellersId } from './Sellers';
import type { default as AddressTypeEnum } from './AddressTypeEnum';

/** Identifier type for public.seller_addresses */
export type SellerAddressesId = string & { __brand: 'public.seller_addresses' };

/** Represents the table public.seller_addresses */
export default interface SellerAddresses {
  id: SellerAddressesId;

  seller_id: SellersId;

  address_line1: string;

  address_line2: string | null;

  city: string;

  state: string;

  postal_code: string;

  country: string;

  address_type: AddressTypeEnum;
}

/** Represents the initializer for the table public.seller_addresses */
export interface SellerAddressesInitializer {
  id: SellerAddressesId;

  seller_id: SellersId;

  address_line1: string;

  address_line2?: string | null;

  city: string;

  state: string;

  postal_code: string;

  country: string;

  address_type: AddressTypeEnum;
}

/** Represents the mutator for the table public.seller_addresses */
export interface SellerAddressesMutator {
  id?: SellerAddressesId;

  seller_id?: SellersId;

  address_line1?: string;

  address_line2?: string | null;

  city?: string;

  state?: string;

  postal_code?: string;

  country?: string;

  address_type?: AddressTypeEnum;
}
