// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.sellers */
export type SellersId = string & { __brand: 'public.sellers' };

/** Represents the table public.sellers */
export default interface Sellers {
  id: SellersId;

  user_id: UsersId;

  business_name: string;

  business_type: string;

  tax_id: string;

  description: string | null;

  logo_url: string | null;

  rating: string;

  total_reviews: number;

  is_verified: boolean;

  created_at: Date;
}

/** Represents the initializer for the table public.sellers */
export interface SellersInitializer {
  id: SellersId;

  user_id: UsersId;

  business_name: string;

  business_type: string;

  tax_id: string;

  description?: string | null;

  logo_url?: string | null;

  /** Default value: 0 */
  rating?: string;

  /** Default value: 0 */
  total_reviews?: number;

  /** Default value: false */
  is_verified?: boolean;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.sellers */
export interface SellersMutator {
  id?: SellersId;

  user_id?: UsersId;

  business_name?: string;

  business_type?: string;

  tax_id?: string;

  description?: string | null;

  logo_url?: string | null;

  rating?: string;

  total_reviews?: number;

  is_verified?: boolean;

  created_at?: Date;
}
