// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { OrdersId } from "./Orders";
import type { default as ShipmentStatusEnum } from "./ShipmentStatusEnum";

/** Identifier type for public.shipments */
export type ShipmentsId = string & { __brand: "public.shipments" };

/** Represents the table public.shipments */
export default interface Shipments {
  id: ShipmentsId;

  order_id: OrdersId;

  shipment_status: ShipmentStatusEnum;

  carrier: string;

  shipping_date: Date;

  delivered_date: Date | null;

  tracking_details: unknown;
}

/** Represents the initializer for the table public.shipments */
export interface ShipmentsInitializer {
  /** Default value: nextval('shipments_id_seq'::regclass) */
  id: ShipmentsId;

  order_id: OrdersId;

  shipment_status: ShipmentStatusEnum;

  carrier: string;

  /** Default value: CURRENT_TIMESTAMP */
  shipping_date?: Date;

  delivered_date?: Date | null;

  tracking_details: unknown;
}

/** Represents the mutator for the table public.shipments */
export interface ShipmentsMutator {
  id?: ShipmentsId;

  order_id?: OrdersId;

  shipment_status?: ShipmentStatusEnum;

  carrier?: string;

  shipping_date?: Date;

  delivered_date?: Date | null;

  tracking_details?: unknown;
}
