// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.shipping_methods */
export type ShippingMethodsId = string & { __brand: 'public.shipping_methods' };

/** Represents the table public.shipping_methods */
export default interface ShippingMethods {
  id: ShippingMethodsId;

  name: string;

  description: string | null;

  base_costs: string;

  estimated_days_min: number;

  estimated_days_max: number;

  is_active: boolean | null;
}

/** Represents the initializer for the table public.shipping_methods */
export interface ShippingMethodsInitializer {
  id: ShippingMethodsId;

  name: string;

  description?: string | null;

  base_costs: string;

  estimated_days_min: number;

  estimated_days_max: number;

  /** Default value: true */
  is_active?: boolean | null;
}

/** Represents the mutator for the table public.shipping_methods */
export interface ShippingMethodsMutator {
  id?: ShippingMethodsId;

  name?: string;

  description?: string | null;

  base_costs?: string;

  estimated_days_min?: number;

  estimated_days_max?: number;

  is_active?: boolean | null;
}
