// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.shipment_status_enum */
enum ShipmentStatusEnum {
  pending = 'pending',
  in_transit = 'in_transit',
  delivered = 'delivered',
  failed = 'failed',
};

export default ShipmentStatusEnum;
