// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.shopping_carts */
export type ShoppingCartsId = string & { __brand: 'public.shopping_carts' };

/** Represents the table public.shopping_carts */
export default interface ShoppingCarts {
  id: ShoppingCartsId;

  user_id: UsersId;

  created_at: Date;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.shopping_carts */
export interface ShoppingCartsInitializer {
  id: ShoppingCartsId;

  user_id: UsersId;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  updated_at?: Date | null;
}

/** Represents the mutator for the table public.shopping_carts */
export interface ShoppingCartsMutator {
  id?: ShoppingCartsId;

  user_id?: UsersId;

  created_at?: Date;

  updated_at?: Date | null;
}
