// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';
import type { CurrenciesId } from './Currencies';

/** Identifier type for public.user_preferences */
export type UserPreferencesId = string & { __brand: 'public.user_preferences' };

/** Represents the table public.user_preferences */
export default interface UserPreferences {
  id: UserPreferencesId;

  user_id: UsersId;

  preferred_currency_id: CurrenciesId;

  language: string | null;

  timezone: string | null;

  created_at: Date;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.user_preferences */
export interface UserPreferencesInitializer {
  /** Default value: nextval('user_preferences_id_seq'::regclass) */
  id?: UserPreferencesId;

  user_id: UsersId;

  /** Default value: 1 */
  preferred_currency_id?: CurrenciesId;

  /** Default value: 'en'::character varying */
  language?: string | null;

  /** Default value: 'UTC'::character varying */
  timezone?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  updated_at?: Date | null;
}

/** Represents the mutator for the table public.user_preferences */
export interface UserPreferencesMutator {
  id?: UserPreferencesId;

  user_id?: UsersId;

  preferred_currency_id?: CurrenciesId;

  language?: string | null;

  timezone?: string | null;

  created_at?: Date;

  updated_at?: Date | null;
}
