// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as UserEnum } from "./UserEnum";

/** Identifier type for public.users */
export type UsersId = string & { __brand: "public.users" };

/** Represents the table public.users */
export default interface Users {
  id: UsersId;

  email: string;

  password_hash: string;

  first_name: string | null;

  last_name: string | null;

  phone: string | null;

  created_at: Date | null;

  updated_at: Date | null;

  is_active: boolean | null;

  user_type: UserEnum;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  /** Default value: nextval('users_id_seq'::regclass) */
  id: UsersId;

  email: string;

  password_hash: string;

  first_name?: string | null;

  last_name?: string | null;

  phone?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  updated_at?: Date | null;

  /** Default value: true */
  is_active?: boolean | null;

  user_type: UserEnum;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  id?: UsersId;

  email?: string;

  password_hash?: string;

  first_name?: string | null;

  last_name?: string | null;

  phone?: string | null;

  created_at?: Date | null;

  updated_at?: Date | null;

  is_active?: boolean | null;

  user_type?: UserEnum;
}
