// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';
import type { default as AddressTypeEnum } from './AddressTypeEnum';

/** Identifier type for public.user_addresses */
export type UserAddressesId = string & { __brand: 'public.user_addresses' };

/** Represents the table public.user_addresses */
export default interface UserAddresses {
  id: UserAddressesId;

  user_id: UsersId;

  address_line1: string;

  address_line2: string | null;

  city: string;

  state: string;

  postal_code: string;

  country: string;

  is_default: boolean | null;

  address_type: AddressTypeEnum;

  created_at: Date;
}

/** Represents the initializer for the table public.user_addresses */
export interface UserAddressesInitializer {
  id: UserAddressesId;

  user_id: UsersId;

  address_line1: string;

  address_line2?: string | null;

  city: string;

  state: string;

  postal_code: string;

  country: string;

  /** Default value: false */
  is_default?: boolean | null;

  address_type: AddressTypeEnum;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.user_addresses */
export interface UserAddressesMutator {
  id?: UserAddressesId;

  user_id?: UsersId;

  address_line1?: string;

  address_line2?: string | null;

  city?: string;

  state?: string;

  postal_code?: string;

  country?: string;

  is_default?: boolean | null;

  address_type?: AddressTypeEnum;

  created_at?: Date;
}
