// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.user_enum */
enum UserEnum {
  buyer = 'buyer',
  seller = 'seller',
  admin = 'admin',
};

export default UserEnum;
